### ISSUE TITLE
[TASK] 지도 API 연동 및 마커/info window 구현

### ISSUE THREAD

**Issue by kykapple** [pangyo-children/Colla#116]
## 📃 이슈 내용
- 지도 API 연동
- 마커 구현
- info window 구현

## ✅ 체크 리스트
- [x] 지도 API 연동
- [x] 마커 구현
- [x] info window 구현

**Comment by binimini** [comment]
이슈 이름에는 feat: 안 붙여도 돼서 수정해놓았어요~ (`[REFACTOR], [TASK], [BUG]` 이런식으로 표기해주세요!)
