### ISSUE TITLE
[TASK] 바운더리 좌측 목록과 연동 및 모임 장소 삭제 구현

### ISSUE THREAD

**Issue by kykapple** [pangyo-children/Colla#124]
## 📃 이슈 내용
- 바운더리 좌측 목록과 연동
- 모임 장소 삭제 구현

## ✅ 체크 리스트
- [x]  바운더리 좌측 목록과 연동
- [x]  모임 장소 삭제 구현

**Comment by binimini** [comment]
이슈에는 feat 붙이지 않아도 됩니당~
